import { readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const playgroundRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const repositoryRoot = resolve(playgroundRoot, "..")

async function readJson(relativePath) {
  const content = await readFile(resolve(repositoryRoot, relativePath), "utf8")
  return JSON.parse(content)
}

const [
  entities,
  coreRelationships,
  extensionRelationships,
  contentCatalog,
  sourceCatalog,
  webEvidence,
  scenariosPayload,
  structuredMetrics,
  workEvidence,
] = await Promise.all([
  readJson("track1/data/generated/workbench/mission4_entities.json"),
  readJson("track1/data/generated/workbench/mission4_relationships_core.json"),
  readJson("track1/data/generated/workbench/mission4_relationships_extension.json"),
  readJson("track2/data/generated/manifests/content_catalog.json"),
  readJson("track3/data/source_catalog.json"),
  readJson("track3/data/web_evidence_fixture.json"),
  readJson("track4/data/generated/scenarios.json"),
  readJson("track4/data/generated/tool_a_metrics.json"),
  readJson("track4/data/generated/tool_b_evidence.json"),
])

const relationships = [...coreRelationships, ...extensionRelationships].map((label) => {
  const cleaned = label.replace(/\s+\(logical(?: path)?\)$/, "")
  const [from, relation, to] = cleaned.split(" ")
  return {
    from,
    relation,
    to,
    logical: label.includes("(logical"),
  }
})

const m365SourceCounts = contentCatalog.reduce((counts, item) => {
  counts[item.source] = (counts[item.source] ?? 0) + 1
  return counts
}, {})

const scenarios = scenariosPayload.scenarios.map((scenario) => {
  const catalogEntry = sourceCatalog.scenarios.find(
    (entry) => entry.scenarioId === scenario.id,
  )
  const webEntry = webEvidence.scenarios[scenario.id]
  const metricEntry = structuredMetrics[scenario.id]
  const workEntry = workEvidence[scenario.id]

  if (!catalogEntry || !webEntry || !metricEntry || !workEntry) {
    throw new Error(`Incomplete generated data for ${scenario.id}`)
  }

  return {
    ...scenario,
    metrics: metricEntry,
    workEvidence: workEntry.evidence,
    sourceCoverage: workEntry.sourceCoverage,
    webQuestion: catalogEntry.webQuestion,
    queryTemplate: catalogEntry.queryTemplate,
    interpretationBoundary: catalogEntry.interpretationBoundary,
    webEvidence: webEntry.evidence,
  }
})

const output = {
  sourceAsOf: {
    webCatalog: sourceCatalog.catalogAsOf,
    webFixture: webEvidence.fixtureAsOf,
  },
  stats: {
    iqCount: 4,
    entityCount: entities.length,
    relationshipCount: relationships.length,
    m365ItemCount: contentCatalog.length,
    webCitationCount: Object.values(webEvidence.scenarios).reduce(
      (total, entry) => total + entry.evidence.length,
      0,
    ),
    scenarioCount: scenarios.length,
    strictGateCount: 8,
  },
  ontology: {
    entities,
    relationships,
  },
  m365SourceCounts,
  fixtureNotice: webEvidence.fixtureNotice,
  scenarios,
}

const generatedModule = `// Generated by scripts/generate-data.mjs. Do not edit manually.
export const workshopData = ${JSON.stringify(output, null, 2)} as const
`

await writeFile(
  resolve(playgroundRoot, "src/data/generated.ts"),
  generatedModule,
  "utf8",
)

console.log(
  `[Microsoft IQ Playground] Generated ${entities.length} entities, ${relationships.length} relationships, ${contentCatalog.length} M365 items, and ${output.stats.webCitationCount} citations.`,
)
