// Generated by scripts/generate-data.mjs. Do not edit manually.
export const workshopData = {
  "sourceAsOf": {
    "webCatalog": "2026-07-28",
    "webFixture": "2026-07-28T15:00:00+09:00"
  },
  "stats": {
    "iqCount": 4,
    "entityCount": 14,
    "relationshipCount": 23,
    "m365ItemCount": 60,
    "webCitationCount": 6,
    "scenarioCount": 3,
    "strictGateCount": 8
  },
  "ontology": {
    "entities": [
      "Customer",
      "Product",
      "Channel",
      "Campaign",
      "Promotion",
      "Order",
      "OrderItem",
      "Payment",
      "Shipment",
      "Return",
      "SupportTicket",
      "InventorySnapshot",
      "OrderPromotion",
      "CampaignAttribution"
    ],
    "relationships": [
      {
        "from": "Customer",
        "relation": "places",
        "to": "Order",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "belongs_to",
        "to": "Channel",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "has",
        "to": "Payment",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "fulfilled_by",
        "to": "Shipment",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "includes",
        "to": "OrderItem",
        "logical": false
      },
      {
        "from": "OrderItem",
        "relation": "references",
        "to": "Product",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "has",
        "to": "Return",
        "logical": false
      },
      {
        "from": "Return",
        "relation": "references",
        "to": "Product",
        "logical": false
      },
      {
        "from": "Return",
        "relation": "requested_by",
        "to": "Customer",
        "logical": false
      },
      {
        "from": "Customer",
        "relation": "raises",
        "to": "SupportTicket",
        "logical": false
      },
      {
        "from": "SupportTicket",
        "relation": "relates_to",
        "to": "Order",
        "logical": false
      },
      {
        "from": "Product",
        "relation": "has",
        "to": "InventorySnapshot",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "receives",
        "to": "OrderPromotion",
        "logical": false
      },
      {
        "from": "OrderPromotion",
        "relation": "points_to",
        "to": "Promotion",
        "logical": false
      },
      {
        "from": "Campaign",
        "relation": "drives",
        "to": "CampaignAttribution",
        "logical": false
      },
      {
        "from": "CampaignAttribution",
        "relation": "points_to",
        "to": "Order",
        "logical": false
      },
      {
        "from": "CampaignAttribution",
        "relation": "points_to",
        "to": "Customer",
        "logical": false
      },
      {
        "from": "Promotion",
        "relation": "influences",
        "to": "Order",
        "logical": true
      },
      {
        "from": "Campaign",
        "relation": "influences",
        "to": "Order",
        "logical": true
      },
      {
        "from": "Customer",
        "relation": "purchases",
        "to": "Product",
        "logical": true
      },
      {
        "from": "Payment",
        "relation": "relates_to",
        "to": "Return",
        "logical": true
      },
      {
        "from": "Shipment",
        "relation": "relates_to",
        "to": "Return",
        "logical": true
      },
      {
        "from": "Order",
        "relation": "applies",
        "to": "Promotion",
        "logical": true
      }
    ]
  },
  "m365SourceCounts": {
    "SharePoint": 15,
    "OneDrive": 12,
    "Outlook": 15,
    "Teams": 18
  },
  "fixtureNotice": "교육용 evidence 계약 fixture이며 현재 장애, 경보, 리콜의 존재를 주장하지 않습니다. live 실행에서는 실제 검색 결과와 URL citation으로 교체하십시오.",
  "scenarios": [
    {
      "id": "Q1",
      "question": "결제 실패가 캠페인 전환율에 미치는 영향은 무엇인가?",
      "goal": "캠페인별 전환율과 결제 실패 패턴 비교",
      "keywords": [
        "SummerPush",
        "VIPRetention",
        "결제",
        "payment",
        "전환율"
      ],
      "semanticKeys": [
        "CampaignId",
        "OrderId",
        "PaymentStatus"
      ],
      "metrics": {
        "scenarioId": "Q1",
        "title": "결제 실패-전환율 영향 분석",
        "highlights": [
          "핵심 캠페인 0개를 비교했고 최고 전환율은 -, 최저 전환율은 -이다.",
          "payment_status가 Success/RetrySuccess가 아닌 주문은 결제 실패/미확정으로 분류했다."
        ],
        "perCampaign": []
      },
      "workEvidence": [
        {
          "id": "TM06",
          "source": "Teams",
          "title": "SummerPush 중간 성과 해석",
          "businessDate": "2026-05-20T15:00:00+09:00",
          "owner": "한유진",
          "location": "teams/threads.json",
          "target": "campaign-ops"
        },
        {
          "id": "SP02",
          "source": "SharePoint",
          "title": "SummerPush 중간 성과 리포트",
          "businessDate": "2026-05-20",
          "owner": "한유진",
          "location": "sharepoint/Campaigns/02_SummerPush_Mid_Campaign_Performance_Report.docx",
          "target": "/Track2-Sample/Campaigns/02_SummerPush_Mid_Campaign_Performance_Report.docx"
        },
        {
          "id": "EM01",
          "source": "Outlook",
          "title": "[리더십] 5월 매출 급락 이슈 공유",
          "businessDate": "2026-05-18T08:40:00+09:00",
          "owner": "김서연",
          "location": "outlook/EM01_sales-drop_message.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "OD04",
          "source": "OneDrive",
          "title": "캠페인 주간 성과 리뷰 노트",
          "businessDate": "2026-05-21",
          "owner": "한유진",
          "location": "onedrive/MeetingNotes/04_Weekly_Campaign_Performance_Review_Notes.docx",
          "target": "/Track2-Sample/MeetingNotes/04_Weekly_Campaign_Performance_Review_Notes.docx"
        },
        {
          "id": "SP01",
          "source": "SharePoint",
          "title": "SummerPush 캠페인 킥오프 기획서",
          "businessDate": "2026-04-15",
          "owner": "최민석",
          "location": "sharepoint/Campaigns/01_SummerPush_Campaign_Kickoff_Plan.docx",
          "target": "/Track2-Sample/Campaigns/01_SummerPush_Campaign_Kickoff_Plan.docx"
        },
        {
          "id": "SP10",
          "source": "SharePoint",
          "title": "결제 실패 및 재시도 사후 분석",
          "businessDate": "2026-05-21",
          "owner": "정도윤",
          "location": "sharepoint/Operations/10_Payment_Failure_and_Retry_Postmortem.docx",
          "target": "/Track2-Sample/Operations/10_Payment_Failure_and_Retry_Postmortem.docx"
        },
        {
          "id": "EM03",
          "source": "Outlook",
          "title": "결제 실패 급증 관련 결제팀 1차 회신",
          "businessDate": "2026-05-19T09:20:00+09:00",
          "owner": "정도윤",
          "location": "outlook/EM03_payment-incident_message.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "OD02",
          "source": "OneDrive",
          "title": "결제 장애 워룸 회의록",
          "businessDate": "2026-05-19",
          "owner": "정도윤",
          "location": "onedrive/MeetingNotes/02_Payment_Incident_War_Room_Notes.docx",
          "target": "/Track2-Sample/MeetingNotes/02_Payment_Incident_War_Room_Notes.docx"
        }
      ],
      "sourceCoverage": {
        "Teams": 1,
        "SharePoint": 3,
        "Outlook": 2,
        "OneDrive": 2
      },
      "webQuestion": "분석 기간에 외부 결제 서비스의 공식 장애 공지가 있었는가?",
      "queryTemplate": "공식 결제 서비스 상태 페이지에서 {date_range} 장애 또는 성능 저하 공지를 찾아 발생 시각과 복구 시각을 URL과 함께 보여줘",
      "interpretationBoundary": "내부 결제 제공자가 확인되고 시간대가 일치할 때만 원인 후보로 제시한다.",
      "webEvidence": [
        {
          "id": "WEB-Q1-01",
          "scenarioId": "Q1",
          "title": "Stripe System Status",
          "url": "https://status.stripe.com/",
          "domain": "status.stripe.com",
          "sourceType": "official-provider-status",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "결제 서비스 운영 상태와 사건 이력을 확인할 수 있는 1차 출처 예시입니다.",
          "limitations": [
            "현재 장애를 의미하지 않음",
            "내부 결제 제공자와 시간대 일치 여부를 별도 확인해야 함"
          ]
        },
        {
          "id": "WEB-Q1-02",
          "scenarioId": "Q1",
          "title": "PayPal Status",
          "url": "https://www.paypal-status.com/product/production",
          "domain": "www.paypal-status.com",
          "sourceType": "official-provider-status",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "결제 제품의 운영 상태를 확인할 수 있는 1차 출처 예시입니다.",
          "limitations": [
            "현재 장애를 의미하지 않음",
            "내부 시스템이 PayPal을 사용한다는 근거가 없음"
          ]
        }
      ]
    },
    {
      "id": "Q2",
      "question": "배송 지연은 반품률과 고객 불만 티켓에 어떤 영향을 미치는가?",
      "goal": "배송 지연군의 반품/불만율 확인",
      "keywords": [
        "배송",
        "LateDelivery",
        "logistics",
        "return",
        "ticket"
      ],
      "semanticKeys": [
        "OrderId",
        "DeliveryStatus",
        "ReturnId",
        "TicketId"
      ],
      "metrics": {
        "scenarioId": "Q2",
        "title": "배송 지연 영향 분석",
        "highlights": [
          "배송 지연 주문 666건 중 반품 발생 비율은 43.54%이다.",
          "배송 지연 주문의 COMPLAINT 티켓 비율은 31.83%이다."
        ],
        "delayedOrderCount": 666,
        "delayedReturnRatePct": 43.54,
        "delayedComplaintRatePct": 31.83,
        "topDelayedReturnReasons": [
          {
            "reason": "LateDelivery",
            "count": 160
          },
          {
            "reason": "Damaged",
            "count": 124
          },
          {
            "reason": "NotAsDescribed",
            "count": 104
          }
        ]
      },
      "workEvidence": [
        {
          "id": "TM18",
          "source": "Teams",
          "title": "주문 취소율과 배송 지연 상관 점검",
          "businessDate": "2026-05-24T14:00:00+09:00",
          "owner": "한유진",
          "location": "teams/threads.json",
          "target": "campaign-ops"
        },
        {
          "id": "SP06",
          "source": "SharePoint",
          "title": "배송 지연 원인 분석 및 고객 영향",
          "businessDate": "2026-05-23",
          "owner": "윤가영",
          "location": "sharepoint/Operations/06_Delivery_Delay_Root_Cause_and_Customer_Impact.docx",
          "target": "/Track2-Sample/Operations/06_Delivery_Delay_Root_Cause_and_Customer_Impact.docx"
        },
        {
          "id": "EM07",
          "source": "Outlook",
          "title": "반품 사유 월간 요약 - 채널 및 고객등급 검토",
          "businessDate": "2026-05-25T16:30:00+09:00",
          "owner": "배수민",
          "location": "outlook/EM07_returns_message.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "OD05",
          "source": "OneDrive",
          "title": "반품 VOC 분류 워크숍 노트",
          "businessDate": "2026-05-25",
          "owner": "배수민",
          "location": "onedrive/MeetingNotes/05_Return_VOC_Classification_Workshop_Notes.docx",
          "target": "/Track2-Sample/MeetingNotes/05_Return_VOC_Classification_Workshop_Notes.docx"
        },
        {
          "id": "EM06",
          "source": "Outlook",
          "title": "RE: [긴급] 핵심 상품 재고 부족 및 캠페인 노출 조정 요청",
          "businessDate": "2026-05-17T08:50:00+09:00",
          "owner": "윤가영",
          "location": "outlook/EM06_stockout_reply.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "OD03",
          "source": "OneDrive",
          "title": "재고·물류·CS 합동 회의록",
          "businessDate": "2026-05-17",
          "owner": "오지훈",
          "location": "onedrive/MeetingNotes/03_Inventory_Logistics_CS_Joint_Meeting_Notes.docx",
          "target": "/Track2-Sample/MeetingNotes/03_Inventory_Logistics_CS_Joint_Meeting_Notes.docx"
        },
        {
          "id": "TM01",
          "source": "Teams",
          "title": "AeroPhone X 배송 지연 클레임",
          "businessDate": "2026-05-20T09:05:00+09:00",
          "owner": "배수민",
          "location": "teams/threads.json",
          "target": "cs-tier2"
        },
        {
          "id": "TM03",
          "source": "Teams",
          "title": "UltraBook 15 배송 추적 갱신",
          "businessDate": "2026-05-17T08:35:00+09:00",
          "owner": "윤가영",
          "location": "teams/threads.json",
          "target": "logistics"
        }
      ],
      "sourceCoverage": {
        "Teams": 3,
        "SharePoint": 1,
        "Outlook": 2,
        "OneDrive": 2
      },
      "webQuestion": "분석 기간과 배송 지역에 공식 기상 또는 교통 경보가 있었는가?",
      "queryTemplate": "{date_range} {region} 공식 기상 경보와 항공·교통 운영 공지를 찾아 적용 지역과 시간을 URL과 함께 보여줘",
      "interpretationBoundary": "샘플 데이터에 지역이 없으면 외부 사건을 배송 지연의 직접 원인으로 단정하지 않는다.",
      "webEvidence": [
        {
          "id": "WEB-Q2-01",
          "scenarioId": "Q2",
          "title": "National Weather Service Active Alerts API",
          "url": "https://api.weather.gov/alerts/active",
          "domain": "api.weather.gov",
          "sourceType": "official-government-alert",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "활성 기상 경보를 시간과 지역 기준으로 확인할 수 있는 공식 API 예시입니다.",
          "limitations": [
            "현재 특정 경보를 주장하지 않음",
            "샘플 배송 데이터에는 지역 컬럼이 없음"
          ]
        },
        {
          "id": "WEB-Q2-02",
          "scenarioId": "Q2",
          "title": "FAA National Airspace System Status",
          "url": "https://nasstatus.faa.gov/",
          "domain": "nasstatus.faa.gov",
          "sourceType": "official-government-status",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "공항과 국가 공역 운영 이벤트를 확인할 수 있는 공식 상태 출처 예시입니다.",
          "limitations": [
            "현재 운송 장애를 의미하지 않음",
            "워크숍 배송이 항공 운송이라는 근거가 없음"
          ]
        }
      ]
    },
    {
      "id": "Q3",
      "question": "Q3 핵심 상품 3종의 매출/반품 신호를 어떻게 해석할 것인가?",
      "goal": "AeroPhone X/SmartWatch Pro/UltraBook 15 성과 비교",
      "keywords": [
        "AeroPhone X",
        "SmartWatch Pro",
        "UltraBook 15",
        "Q3",
        "제품"
      ],
      "semanticKeys": [
        "ProductId",
        "OrderId",
        "ReturnId"
      ],
      "metrics": {
        "scenarioId": "Q3",
        "title": "핵심 상품 3종 성과 비교",
        "highlights": [
          "Q3 핵심 상품 3종(AeroPhone X, SmartWatch Pro, UltraBook 15)을 동일 기준으로 비교했다.",
          "주문 수, 매출, 반품률을 함께 보고 대응 우선순위를 선정한다."
        ],
        "perProduct": [
          {
            "productName": "AeroPhone X",
            "orderCount": 3,
            "units": 4,
            "salesAmount": 114,
            "returnCount": 1,
            "returnRatePct": 33.33
          },
          {
            "productName": "SmartWatch Pro",
            "orderCount": 2,
            "units": 3,
            "salesAmount": 96.6,
            "returnCount": 0,
            "returnRatePct": 0
          },
          {
            "productName": "UltraBook 15",
            "orderCount": 6,
            "units": 11,
            "salesAmount": 150.7,
            "returnCount": 2,
            "returnRatePct": 33.33
          }
        ]
      },
      "workEvidence": [
        {
          "id": "SP12",
          "source": "SharePoint",
          "title": "Q3 리더십 운영 리스크 브리핑",
          "businessDate": "2026-07-11",
          "owner": "이현지",
          "location": "sharepoint/Leadership/12_Q3_Leadership_Operational_Risk_Briefing.docx",
          "target": "/Track2-Sample/Leadership/12_Q3_Leadership_Operational_Risk_Briefing.docx"
        },
        {
          "id": "EM12",
          "source": "Outlook",
          "title": "RE: BackToSchool 캠페인 조건부 승인 요청",
          "businessDate": "2026-07-11T09:30:00+09:00",
          "owner": "김서연",
          "location": "outlook/EM12_backtoschool_reply.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "OD03",
          "source": "OneDrive",
          "title": "재고·물류·CS 합동 회의록",
          "businessDate": "2026-05-17",
          "owner": "오지훈",
          "location": "onedrive/MeetingNotes/03_Inventory_Logistics_CS_Joint_Meeting_Notes.docx",
          "target": "/Track2-Sample/MeetingNotes/03_Inventory_Logistics_CS_Joint_Meeting_Notes.docx"
        },
        {
          "id": "TM04",
          "source": "Teams",
          "title": "핵심 상품 품절 임박 공동 대응",
          "businessDate": "2026-05-16T09:00:00+09:00",
          "owner": "오지훈",
          "location": "teams/threads.json",
          "target": "inventory"
        },
        {
          "id": "EM05",
          "source": "Outlook",
          "title": "[긴급] 핵심 상품 재고 부족 및 캠페인 노출 조정 요청",
          "businessDate": "2026-05-16T09:15:00+09:00",
          "owner": "오지훈",
          "location": "outlook/EM05_stockout_message.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "TM01",
          "source": "Teams",
          "title": "AeroPhone X 배송 지연 클레임",
          "businessDate": "2026-05-20T09:05:00+09:00",
          "owner": "배수민",
          "location": "teams/threads.json",
          "target": "cs-tier2"
        },
        {
          "id": "TM03",
          "source": "Teams",
          "title": "UltraBook 15 배송 추적 갱신",
          "businessDate": "2026-05-17T08:35:00+09:00",
          "owner": "윤가영",
          "location": "teams/threads.json",
          "target": "logistics"
        },
        {
          "id": "EM11",
          "source": "Outlook",
          "title": "UltraBook 15 공급 일정 및 고객 공지 기준",
          "businessDate": "2026-05-16T13:45:00+09:00",
          "owner": "오지훈",
          "location": "outlook/EM11_ultrabook-vendor_message.eml",
          "target": "Configured sample recipients"
        }
      ],
      "sourceCoverage": {
        "SharePoint": 1,
        "Outlook": 3,
        "OneDrive": 1,
        "Teams": 3
      },
      "webQuestion": "전자제품 범주의 공식 안전 공지나 사이버보안 지침이 있는가?",
      "queryTemplate": "{date_range} 스마트폰 스마트워치 노트북 범주의 공식 안전 리콜 또는 사이버보안 지침을 URL과 함께 보여줘",
      "interpretationBoundary": "AeroPhone X, SmartWatch Pro, UltraBook 15는 가상 상품이므로 외부 공지는 범주 수준 참고로만 사용한다.",
      "webEvidence": [
        {
          "id": "WEB-Q3-01",
          "scenarioId": "Q3",
          "title": "U.S. Consumer Product Safety Commission Recalls",
          "url": "https://www.cpsc.gov/Recalls",
          "domain": "www.cpsc.gov",
          "sourceType": "official-regulator",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "제품 범주의 공식 리콜 공지를 확인할 수 있는 규제기관 출처 예시입니다.",
          "limitations": [
            "가상 상품에 대한 리콜을 의미하지 않음",
            "실제 제품명과 모델 번호가 일치해야 직접 근거로 사용할 수 있음"
          ]
        },
        {
          "id": "WEB-Q3-02",
          "scenarioId": "Q3",
          "title": "NIST Cybersecurity for IoT Program",
          "url": "https://www.nist.gov/itl/applied-cybersecurity/nist-cybersecurity-iot-program",
          "domain": "www.nist.gov",
          "sourceType": "official-standards-guidance",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "스마트 연결 제품 범주의 사이버보안 지침을 확인할 수 있는 공식 출처 예시입니다.",
          "limitations": [
            "내부 반품 신호의 원인을 설명하지 않음",
            "스마트워치 등 연결 제품 범주 수준의 참고로만 사용"
          ]
        }
      ]
    }
  ],
  "industryScenarios": [
    {
      "id": "MFG-01",
      "title": "제조: 품질 이상 조기 감지 및 원인 후보 검증",
      "sections": {
        "업무 배경·범위": "품질 책임자와 생산 책임자는 특정 제품군, 생산라인, 교대, 작업지시, 공정 단계,\n설비, 원자재 lot, 분석 기간을 정합니다. 목표는 불량 신호가 기준선에서 벗어났을 때\n원인을 단정하지 않고, 생산·설비·자재·검사 관점의 원인 후보를 검증하는 것입니다.",
        "탐지 신호와 핵심 질문": "- 불량률, first-pass yield, 재작업률 또는 결함 코드 분포가 조직의 기준선에서\n  의미 있게 벗어났는가?\n- 같은 기간의 공정·설비·교대·원자재 lot 변화가 신호와 시간적으로 겹치는가?\n- 작업 SOP 또는 검사 기준의 편차를 뒷받침하는 내부 근거가 있는가?\n- 출하 보류, 추가 검사, CAPA 개시가 필요한 수준인가?",
        "FabricIQ — 정형 신호": "| 설계 요소 | 내용 |\n| --- | --- |\n| 주요 데이터 | 제품, 작업지시, 생산실적, 공정 단계, 검사 결과, 결함 코드, 설비 상태·정지, 보전 이력, 원자재 lot, 공급사 |\n| 핵심 KPI | 불량률, first-pass yield, 재작업률, 결함 코드별 비중, 설비 정지·경보 패턴 |\n| 비교 기준 | 제품군·라인·교대·공정별 기준선과 이전 정상 기간 또는 유사 작업지시 |\n| 예시 관계 경로 | **Product → WorkOrder → ProcessStep → Equipment → Inspection**, **MaterialLot → Supplier**, **WorkOrder → Shift** |\n\nFabricIQ는 이상 신호와 관계 경로를 검증합니다. 단일 지표의 변화만으로 특정 설비,\n작업자, 공급사 또는 SOP 위반을 원인으로 확정하지 않습니다.",
        "WorkIQ — 내부 업무 맥락": "ACL이 적용된 교대 인수인계, 품질 huddle 회의록, CAPA 기록, 작업지침과 개정 이력,\n공정 변경 승인, 설비 보전 기록, 공급사 품질 협의 문서를 검색합니다. 다음 사항을\n확인합니다.\n\n- 설정값·작업 순서·검사 조건·대체 자재·검사 예외가 승인된 변경으로 기록됐는가?\n- 현장팀이 재현 조건, 일시적 우회, 추가 검사 또는 출하 보류를 논의했는가?\n- 품질·생산·보전 책임자와 현재 조치 상태가 문서 근거로 확인되는가?",
        "WebIQ — 공개 확인": "공개 질문은 제품명·lot·내부 불량률을 제외한 일반화된 형태로 만듭니다. 예를 들어\n같은 기간과 관할에서 관련 안전 공지·리콜·원자재 품질 공지가 있었는지, 또는\n승인된 공급사·운송 구간에 공개적인 공급 위험 공지가 있었는지를 확인합니다. 규제기관\n안전 공지, 공급사의 공식 품질 공지, 공식 운송·기상 공지를 우선합니다.\n\n시간, 제품 범주, 공급 범위가 일치하지 않으면 외부 근거는 원인 후보가 아니라\n추가 확인 항목으로만 표시합니다.",
        "FoundryIQ — 정책 대조와 승인 조치": "FoundryIQ는 품질 SOP, 검사 기준, 변경관리 정책, 출하 보류 기준, CAPA 절차의\n현재 버전과 FabricIQ·WorkIQ 근거를 대조합니다. 결과는 **SOP 위반 확정**이 아니라\n**추가 확인이 필요한 편차**, **정책과 일치하는 조치**, **근거 불충분**으로 표현합니다.\n\n품질 책임자가 승인할 수 있도록 lot 격리, 추가 검사, 영향 범위 확인, CAPA 개시\n후보를 제안합니다. 시스템이 자동으로 출하를 차단하거나 CAPA를 종결하지 않습니다.",
        "완료 기준": "브리핑에 지표의 분석 단위·비교 기준, 관련 문서 링크, 공개 근거의 범위, SOP 대조\n결과, 품질 책임자의 승인 지점이 분리되어 있으면 완료입니다."
      }
    },
    {
      "id": "LOG-01",
      "title": "물류: 배송 지연 사전 예측 및 대응",
      "sections": {
        "업무 배경·범위": "물류 운영 책임자와 고객 서비스 책임자는 주문, 출고 노드, 재고, 운송사, 노선·구간,\n배송권역, ETA와 분석 기간을 정합니다. 목표는 지연 위험 주문을 우선순위화하고,\n고객 영향이 커지기 전에 승인된 대응안을 준비하는 것입니다.",
        "탐지 신호와 핵심 질문": "- 정시배송률 또는 예측 ETA 대비 편차가 기준선에서 악화됐는가?\n- 특정 허브 체류, 운송 예외, 재고·출고 제약, 노선·운송사 패턴이 겹치는가?\n- 지연 위험이 취소, 반품, 문의, SLA 위반 가능성에 미치는 영향은 무엇인가?\n- 재배차, 대체 출고, 선제 안내, 보상 검토 중 어떤 대응을 사람에게 승인 요청할 것인가?",
        "FabricIQ — 정형 신호": "| 설계 요소 | 내용 |\n| --- | --- |\n| 주요 데이터 | 주문, 재고, 출고 노드, 배송, 운송사, 노선, 배송 이벤트, ETA 예측, 운송 예외, 취소·반품·문의 집계 |\n| 핵심 KPI | 정시배송률, 지연 위험 주문 수, ETA 편차, 허브 체류 시간, 운송 예외율, 취소·반품·문의 영향 |\n| 비교 기준 | 배송권역·노선·운송사·서비스 등급별 기준선과 같은 요일 또는 정상 기간 |\n| 예시 관계 경로 | **Order → Shipment → Carrier/Route → DeliveryEvent**, **Inventory → FulfillmentNode → Order** |",
        "WorkIQ — 내부 업무 맥락": "배차·운송사 예외 보고, 창고 backlog 논의, 현장 인수인계, 고객 서비스 공지 초안,\n보상 승인 기록, SLA, 대체 출고 정책을 ACL 범위 안에서 확인합니다. 담당자, 현재\n복구 계획, 운송사와 합의한 조치, 고객 커뮤니케이션 승인 여부를 문서 근거로 검증합니다.",
        "WebIQ — 공개 확인": "시간·지역·노선 정보를 일반화해 공식 기상, 도로·철도·항만·세관 공지, 운송사의\n공식 상태 페이지를 확인합니다. 외부 사건의 시간과 구간이 내부 배송 신호와 맞을 때만\n관련 가능성으로 표시하며, 일치하지 않는 경우에는 원인으로 단정하지 않습니다.",
        "FoundryIQ — 정책 대조와 승인 조치": "FoundryIQ는 SLA, 우선 출고 기준, 대체 운송 정책, 고객 안내·보상 정책을 대조해\n영향이 큰 주문군과 가능한 조치를 제안합니다. 재배차, 우선 출고, 고객 안내, 보상은\n운영·고객 서비스 책임자의 승인 후에만 실행합니다.",
        "완료 기준": "지연 위험의 수치 근거, 내부 운영 상태, 공개 상황의 범위, SLA와 승인 흐름, 고객\n영향 완화 조치가 하나의 브리핑에서 분리되어 있으면 완료입니다."
      }
    },
    {
      "id": "FIN-01",
      "title": "금융: AML/KYC 컴플라이언스 검토 우선순위화",
      "sections": {
        "업무 배경·범위": "준법 책임자 또는 AML 검토 책임자는 승인된 관할, 상품, 고객 위험등급, 분석 기간,\n허용된 가명화 식별자 범위를 정합니다. 목표는 거래·고객 위험 신호를 바탕으로\n검토 대상을 우선순위화하고, 현행 AML/KYC 정책과 승인 흐름에 맞는 검토 패키지를\n만드는 것입니다.",
        "탐지 신호와 핵심 질문": "- 특정 위험군에서 이상 거래 빈도, 거래량, 경보 발생 또는 케이스 적체가 기준선과\n  다르게 나타나는가?\n- KYC 갱신 지연, 예외 승인 비율, 케이스 aging이 정책상 재검토가 필요한 수준인가?\n- 내부 승인·검토 기록은 현재 정책 버전과 일치하는가?\n- 어떤 케이스를 준법 담당자의 추가 조사 또는 에스컬레이션 대상으로 제안할 것인가?",
        "FabricIQ — 정형 신호": "| 설계 요소 | 내용 |\n| --- | --- |\n| 주요 데이터 | 가명화 고객, 계좌, 상품, 거래, 고객 위험등급, 모니터링 경보, 케이스, 승인 상태, KYC 갱신 상태 |\n| 핵심 KPI | 이상 거래 빈도·규모, 경보 발생률, KYC 갱신 지연, 케이스 aging, 예외 승인 비율 |\n| 비교 기준 | 승인된 고객 세그먼트·상품·관할·기간별 기준선과 정책상 검토 임계값 |\n| 예시 관계 경로 | **Customer (pseudonymized) → Account → Transaction → MonitoringAlert → Case → Approval** |",
        "WorkIQ — 내부 업무 맥락": "접근이 허용된 사건 검토 노트, 준법·법무 승인 기록, 정책 예외, 감사 지적, 정책\n버전 관리 문서를 확인합니다. WorkIQ는 누가 어떤 근거로 검토·승인했는지, 보완이\n필요한 문서가 있는지 확인하지만 AML 위험 점수나 법적 결론을 문서에서 계산하지\n않습니다.",
        "WebIQ — 공개 확인": "규제기관, 제재 당국, 공식 법령·가이드의 변경 공지만 확인합니다. 고객명, 거래\n정보, 내부 탐지 규칙, 경보 사유, 미공개 수치는 외부 검색에 전송하지 않습니다.\n외부 규정 변경은 내부 검토 범위나 정책 재검토의 계기가 될 수 있지만, 특정 고객이나\n거래에 대한 결론을 대신하지 않습니다.",
        "FoundryIQ — 정책 대조와 승인 조치": "FoundryIQ는 적용 가능한 AML/KYC 정책 버전, 예외·에스컬레이션 절차, 기록 보존\n기준과 세 근거를 대조합니다. 검토 패키지 보완, 증빙 재확인, 우선 검토, 준법\n에스컬레이션을 제안할 수 있습니다.\n\n법적 결론, 계좌 동결, 거래 제한, 당국 신고·제출은 생성형 응답이나 자동화가\n수행하지 않으며, 권한 있는 준법·법무 담당자가 결정하고 실행합니다.",
        "완료 기준": "가명화·최소 권한 경계, 정책 버전, 우선 검토 근거, 사람의 법적·운영 승인 지점이\n명확하면 완료입니다."
      }
    },
    {
      "id": "HC-01",
      "title": "헬스케어: 집계 운영 안전 리스크 조기 감지",
      "sections": {
        "업무 배경·범위": "환자 안전 책임자와 운영 책임자는 병원, 서비스 라인, 병동, 교대, 분석 기간을\n집계 수준으로 정합니다. 이 시나리오는 병상 운영과 안전 리스크의 조기 감지에\n한정하며, 개별 환자의 진단, 트리아지, 처방, 치료 결정에는 사용하지 않습니다.",
        "탐지 신호와 핵심 질문": "- 병상 점유, boarding, 대기시간, 입·퇴원 흐름, 재입원 추세, 인력 배치, 안전사건\n  집계 중 무엇이 기준선에서 벗어났는가?\n- 특정 병동·교대·서비스 라인에 운영 부담이 집중되는가?\n- 안전 huddle, 용량 에스컬레이션, 감염관리 또는 운영 프로토콜상 확인할 조치가 있는가?\n- 임상·운영 책임자에게 어떤 집계 수준의 에스컬레이션을 제안할 것인가?",
        "FabricIQ — 정형 신호": "| 설계 요소 | 내용 |\n| --- | --- |\n| 주요 데이터 | 시설, 서비스 라인, 병동, 교대, 집계 병상 용량, 입·퇴원 흐름, 대기시간, 인력 계획·커버리지, 비식별 안전사건 집계 |\n| 핵심 KPI | 병상 점유율, boarding·대기시간, 입·퇴원 흐름, 재입원 추세, 계획 대비 인력 커버리지, 안전사건 집계 추세 |\n| 비교 기준 | 병동·교대·서비스 라인별 운영 기준선, 승인된 용량·인력 기준, 정상 기간 |\n| 예시 관계 경로 | **Facility → ServiceLine → Unit → Shift → CapacitySnapshot/SafetyEventAggregate**, **Unit → StaffingPlan → Coverage** |\n\n개별 환자 수준의 식별 가능한 정보는 분석·브리핑에 포함하지 않습니다. 필요한 경우\n조직의 비식별화, 최소 필요 정보, 접근 권한 정책을 먼저 적용합니다.",
        "WorkIQ — 내부 업무 맥락": "안전 huddle, 병상·인력 에스컬레이션, 집계 사고 검토, 감염관리 공지, 운영\n프로토콜, 책임자 승인 기록을 ACL 범위에서 확인합니다. 개인 진료기록이나 면허\n보유 의료진의 전문 판단을 대체하는 근거로 사용하지 않습니다.",
        "WebIQ — 공개 확인": "보건 당국의 감염병·안전 공지, 지역 재난·기상 경보, 공식 규제 변경을 기간·지역·\n대상 범위가 맞는지 확인합니다. 외부 공지는 내부 운영 신호의 맥락일 수 있으나,\n특정 환자 상태 또는 내부 안전사건의 원인으로 단정하지 않습니다.",
        "FoundryIQ — 정책 대조와 승인 조치": "FoundryIQ는 승인된 환자 안전·용량·인력·감염관리 운영 프로토콜과 집계 근거를\n대조해 운영 위험 브리핑과 에스컬레이션 후보를 만듭니다. 추가 인력 요청, 병상\n운영 조정, 안전 검토의 개시는 책임자 승인 대상으로 제안할 수 있습니다.\n\n진단, 트리아지, 처방, 치료 우선순위 결정은 지원하거나 자동화하지 않으며, 모든\n임상 판단은 면허 보유 의료진과 조직의 임상 거버넌스가 맡습니다.",
        "완료 기준": "집계·비식별 범위, 운영 지표, 내부 프로토콜 근거, 외부 상황의 제한, 임상·운영\n책임자의 승인 지점이 명확하면 완료입니다."
      }
    },
    {
      "id": "TEL-01",
      "title": "통신: 네트워크 장애 예측 및 고객 영향 최소화",
      "sections": {
        "업무 배경·범위": "NOC 책임자와 서비스 책임자는 권역, 사이트 또는 셀, 네트워크 요소, 서비스,\n변경창, 분석 기간을 정합니다. 목표는 장애 징후와 집계 고객 영향을 우선순위화해\n검증·복구·커뮤니케이션을 준비하는 것입니다.",
        "탐지 신호와 핵심 질문": "- 가용성, 트래픽·혼잡, 지연, 패킷 손실, handover·통화절단, alarm burst 중 어떤\n  신호가 기준선에서 벗어났는가?\n- 계획된 변경, 현장 작업, 특정 네트워크 요소 또는 지역 이벤트와 시간적으로\n  겹치는가?\n- 영향 등급과 검증 우선순위는 어떻게 정하고, 누구에게 현장 출동이나 고객 안내의\n  승인을 요청할 것인가?",
        "FabricIQ — 정형 신호": "| 설계 요소 | 내용 |\n| --- | --- |\n| 주요 데이터 | 권역, 사이트·셀, 네트워크 요소, 성능 지표, 경보, 계획 변경, 작업지시, 집계 서비스·고객 영향 |\n| 핵심 KPI | 가용성, 트래픽·혼잡, 지연, 패킷 손실, handover·통화절단, alarm burst, 집계 영향 규모 |\n| 비교 기준 | 지역·서비스·요소별 기준선, 변경 전후 창, 정상 시간대 |\n| 예시 관계 경로 | **Region → Site/Cell → NetworkElement → PerformanceMetric/Alarm**, **PlannedChange → WorkOrder → ServiceImpact** |",
        "WorkIQ — 내부 업무 맥락": "NOC bridge 기록, 변경·유지보수 승인, 현장 출동 보고, runbook, 장애 커뮤니케이션\n초안·승인 기록을 확인합니다. WorkIQ 근거로 현재 완화 조치, 담당 팀, 금지된 변경,\n복구 절차를 검증합니다.",
        "WebIQ — 공개 확인": "공식 기상·재난·전력·규제 공지와 승인된 대형 행사 공지를 확인합니다. 경쟁사의\n공개 상태 페이지는 시장 맥락일 수 있지만, 자사 장애의 원인 증거가 아닙니다.\n시간·지역·서비스 범위가 맞지 않는 외부 정보는 가설로도 과장하지 않습니다.",
        "FoundryIQ — 정책 대조와 승인 조치": "FoundryIQ는 runbook, 영향 등급 정책, 변경관리 정책, 장애 커뮤니케이션 절차와\n근거를 대조해 검증 순서, 현장 출동 후보, 고객 안내 초안을 제안합니다. 네트워크\n설정 변경, 현장 출동, 대외 공지는 NOC 또는 권한 있는 책임자의 승인 없이는\n실행하지 않습니다.",
        "완료 기준": "성능 신호, 내부 변경·복구 맥락, 외부 환경의 제한, 영향 등급과 승인 지점이\n명확히 구분되면 완료입니다."
      }
    },
    {
      "id": "RTL-01",
      "title": "리테일: 수요 변화 조기 감지 및 매장·상품 대응 최적화",
      "sections": {
        "업무 배경·범위": "MD, 매장 운영, 공급·재고 책임자는 SKU 또는 상품군, 매장·채널, 지역, 프로모션,\n가격, 재고, 분석 기간을 정합니다. 목표는 수요 변화의 신호를 조기에 확인하고,\n매장·상품 대응의 우선순위를 사람에게 제안하는 것입니다.",
        "탐지 신호와 핵심 질문": "- 매출·수요 예측 편차, sell-through, 재고 가용성·품절, 마진, 취소·반품·문의,\n  채널 전환 중 어떤 신호가 기준선에서 벗어났는가?\n- 가격·프로모션·진열·보충·공급 제약 또는 지역별 수요 변화와 시점이 겹치는가?\n- 어떤 SKU·매장·채널을 우선 확인하고, 배분·보충·프로모션·안내 중 무엇을\n  승인 대상 조치로 제안할 것인가?",
        "FabricIQ — 정형 신호": "| 설계 요소 | 내용 |\n| --- | --- |\n| 주요 데이터 | SKU·상품군, 매장·채널, 재고, 판매 주문, 가격, 프로모션, 반품, 취소, 집계 고객 문의 |\n| 핵심 KPI | 수요 예측 편차, sell-through, 재고 가용성·품절, 마진 지표, 취소·반품·문의, 채널 전환 |\n| 비교 기준 | 상품·매장·채널·지역·프로모션별 기준선과 유사 기간 |\n| 예시 관계 경로 | **Product/SKU → Store/Channel → Inventory → SalesOrder → Promotion/Price → Return/SupportCase** |",
        "WorkIQ — 내부 업무 맥락": "점장 일일 보고, MD 협업, 프로모션 캘린더, 가격·마진 승인, 공급·보충 이슈,\n반품 분석, 매장 운영 공지를 확인합니다. WorkIQ는 현장 관찰, 이미 승인된 계획,\n실행 중인 조치와 담당자를 확인하며, 문서만으로 매출·마진 수치를 계산하지 않습니다.",
        "WebIQ — 공개 확인": "공개 경쟁사 가격·재고는 이용 약관과 관찰 시각을 지키며 확인하고, 공식 트렌드,\n기상, 지역 행사 정보를 보조 근거로 수집합니다. 외부 동향은 내부 수요 변화의\n확정 원인이 아니며, 상품·지역·기간 범위가 맞을 때만 관련 가능성을 설명합니다.",
        "FoundryIQ — 정책 대조와 승인 조치": "FoundryIQ는 가격·마진 가드레일, 재고 배분·보충 정책, 프로모션 승인 기준,\n고객 안내 정책과 세 근거를 대조합니다. 배분, 보충, 진열, 프로모션, 가격 변경,\n발주 또는 고객 안내는 책임자의 승인 후에만 실행하도록 제안합니다.",
        "완료 기준": "수요 신호와 비교 기준, 현장·MD 근거, 공개 맥락의 한계, 가격·마진·재고 정책,\n사람 승인 조치가 분리된 브리핑으로 제공되면 완료입니다."
      }
    }
  ]
} as const
