// Generated by scripts/generate-data.mjs. Do not edit manually.
export const workshopData = {
  "sourceAsOf": {
    "webCatalog": "2026-07-28",
    "webFixture": "2026-07-28T15:00:00+09:00"
  },
  "stats": {
    "iqCount": 4,
    "entityCount": 14,
    "relationshipCount": 23,
    "m365ItemCount": 60,
    "webCitationCount": 6,
    "scenarioCount": 3,
    "strictGateCount": 8
  },
  "ontology": {
    "entities": [
      "Customer",
      "Product",
      "Channel",
      "Campaign",
      "Promotion",
      "Order",
      "OrderItem",
      "Payment",
      "Shipment",
      "Return",
      "SupportTicket",
      "InventorySnapshot",
      "OrderPromotion",
      "CampaignAttribution"
    ],
    "relationships": [
      {
        "from": "Customer",
        "relation": "places",
        "to": "Order",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "belongs_to",
        "to": "Channel",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "has",
        "to": "Payment",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "fulfilled_by",
        "to": "Shipment",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "includes",
        "to": "OrderItem",
        "logical": false
      },
      {
        "from": "OrderItem",
        "relation": "references",
        "to": "Product",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "has",
        "to": "Return",
        "logical": false
      },
      {
        "from": "Return",
        "relation": "references",
        "to": "Product",
        "logical": false
      },
      {
        "from": "Return",
        "relation": "requested_by",
        "to": "Customer",
        "logical": false
      },
      {
        "from": "Customer",
        "relation": "raises",
        "to": "SupportTicket",
        "logical": false
      },
      {
        "from": "SupportTicket",
        "relation": "relates_to",
        "to": "Order",
        "logical": false
      },
      {
        "from": "Product",
        "relation": "has",
        "to": "InventorySnapshot",
        "logical": false
      },
      {
        "from": "Order",
        "relation": "receives",
        "to": "OrderPromotion",
        "logical": false
      },
      {
        "from": "OrderPromotion",
        "relation": "points_to",
        "to": "Promotion",
        "logical": false
      },
      {
        "from": "Campaign",
        "relation": "drives",
        "to": "CampaignAttribution",
        "logical": false
      },
      {
        "from": "CampaignAttribution",
        "relation": "points_to",
        "to": "Order",
        "logical": false
      },
      {
        "from": "CampaignAttribution",
        "relation": "points_to",
        "to": "Customer",
        "logical": false
      },
      {
        "from": "Promotion",
        "relation": "influences",
        "to": "Order",
        "logical": true
      },
      {
        "from": "Campaign",
        "relation": "influences",
        "to": "Order",
        "logical": true
      },
      {
        "from": "Customer",
        "relation": "purchases",
        "to": "Product",
        "logical": true
      },
      {
        "from": "Payment",
        "relation": "relates_to",
        "to": "Return",
        "logical": true
      },
      {
        "from": "Shipment",
        "relation": "relates_to",
        "to": "Return",
        "logical": true
      },
      {
        "from": "Order",
        "relation": "applies",
        "to": "Promotion",
        "logical": true
      }
    ]
  },
  "m365SourceCounts": {
    "SharePoint": 15,
    "OneDrive": 12,
    "Outlook": 15,
    "Teams": 18
  },
  "fixtureNotice": "교육용 evidence 계약 fixture이며 현재 장애, 경보, 리콜의 존재를 주장하지 않습니다. live 실행에서는 실제 검색 결과와 URL citation으로 교체하십시오.",
  "scenarios": [
    {
      "id": "Q1",
      "question": "결제 실패가 캠페인 전환율에 미치는 영향은 무엇인가?",
      "goal": "캠페인별 전환율과 결제 실패 패턴 비교",
      "keywords": [
        "SummerPush",
        "VIPRetention",
        "결제",
        "payment",
        "전환율"
      ],
      "semanticKeys": [
        "CampaignId",
        "OrderId",
        "PaymentStatus"
      ],
      "metrics": {
        "scenarioId": "Q1",
        "title": "결제 실패-전환율 영향 분석",
        "highlights": [
          "핵심 캠페인 0개를 비교했고 최고 전환율은 -, 최저 전환율은 -이다.",
          "payment_status가 Success/RetrySuccess가 아닌 주문은 결제 실패/미확정으로 분류했다."
        ],
        "perCampaign": []
      },
      "workEvidence": [
        {
          "id": "TM06",
          "source": "Teams",
          "title": "SummerPush 중간 성과 해석",
          "businessDate": "2026-05-20T15:00:00+09:00",
          "owner": "한유진",
          "location": "teams/threads.json",
          "target": "campaign-ops"
        },
        {
          "id": "SP02",
          "source": "SharePoint",
          "title": "SummerPush 중간 성과 리포트",
          "businessDate": "2026-05-20",
          "owner": "한유진",
          "location": "sharepoint/Campaigns/02_SummerPush_Mid_Campaign_Performance_Report.docx",
          "target": "/Track2-Sample/Campaigns/02_SummerPush_Mid_Campaign_Performance_Report.docx"
        },
        {
          "id": "EM01",
          "source": "Outlook",
          "title": "[리더십] 5월 매출 급락 이슈 공유",
          "businessDate": "2026-05-18T08:40:00+09:00",
          "owner": "김서연",
          "location": "outlook/EM01_sales-drop_message.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "OD04",
          "source": "OneDrive",
          "title": "캠페인 주간 성과 리뷰 노트",
          "businessDate": "2026-05-21",
          "owner": "한유진",
          "location": "onedrive/MeetingNotes/04_Weekly_Campaign_Performance_Review_Notes.docx",
          "target": "/Track2-Sample/MeetingNotes/04_Weekly_Campaign_Performance_Review_Notes.docx"
        },
        {
          "id": "SP01",
          "source": "SharePoint",
          "title": "SummerPush 캠페인 킥오프 기획서",
          "businessDate": "2026-04-15",
          "owner": "최민석",
          "location": "sharepoint/Campaigns/01_SummerPush_Campaign_Kickoff_Plan.docx",
          "target": "/Track2-Sample/Campaigns/01_SummerPush_Campaign_Kickoff_Plan.docx"
        },
        {
          "id": "SP10",
          "source": "SharePoint",
          "title": "결제 실패 및 재시도 사후 분석",
          "businessDate": "2026-05-21",
          "owner": "정도윤",
          "location": "sharepoint/Operations/10_Payment_Failure_and_Retry_Postmortem.docx",
          "target": "/Track2-Sample/Operations/10_Payment_Failure_and_Retry_Postmortem.docx"
        },
        {
          "id": "EM03",
          "source": "Outlook",
          "title": "결제 실패 급증 관련 결제팀 1차 회신",
          "businessDate": "2026-05-19T09:20:00+09:00",
          "owner": "정도윤",
          "location": "outlook/EM03_payment-incident_message.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "OD02",
          "source": "OneDrive",
          "title": "결제 장애 워룸 회의록",
          "businessDate": "2026-05-19",
          "owner": "정도윤",
          "location": "onedrive/MeetingNotes/02_Payment_Incident_War_Room_Notes.docx",
          "target": "/Track2-Sample/MeetingNotes/02_Payment_Incident_War_Room_Notes.docx"
        }
      ],
      "sourceCoverage": {
        "Teams": 1,
        "SharePoint": 3,
        "Outlook": 2,
        "OneDrive": 2
      },
      "webQuestion": "분석 기간에 외부 결제 서비스의 공식 장애 공지가 있었는가?",
      "queryTemplate": "공식 결제 서비스 상태 페이지에서 {date_range} 장애 또는 성능 저하 공지를 찾아 발생 시각과 복구 시각을 URL과 함께 보여줘",
      "interpretationBoundary": "내부 결제 제공자가 확인되고 시간대가 일치할 때만 원인 후보로 제시한다.",
      "webEvidence": [
        {
          "id": "WEB-Q1-01",
          "scenarioId": "Q1",
          "title": "Stripe System Status",
          "url": "https://status.stripe.com/",
          "domain": "status.stripe.com",
          "sourceType": "official-provider-status",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "결제 서비스 운영 상태와 사건 이력을 확인할 수 있는 1차 출처 예시입니다.",
          "limitations": [
            "현재 장애를 의미하지 않음",
            "내부 결제 제공자와 시간대 일치 여부를 별도 확인해야 함"
          ]
        },
        {
          "id": "WEB-Q1-02",
          "scenarioId": "Q1",
          "title": "PayPal Status",
          "url": "https://www.paypal-status.com/product/production",
          "domain": "www.paypal-status.com",
          "sourceType": "official-provider-status",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "결제 제품의 운영 상태를 확인할 수 있는 1차 출처 예시입니다.",
          "limitations": [
            "현재 장애를 의미하지 않음",
            "내부 시스템이 PayPal을 사용한다는 근거가 없음"
          ]
        }
      ]
    },
    {
      "id": "Q2",
      "question": "배송 지연은 반품률과 고객 불만 티켓에 어떤 영향을 미치는가?",
      "goal": "배송 지연군의 반품/불만율 확인",
      "keywords": [
        "배송",
        "LateDelivery",
        "logistics",
        "return",
        "ticket"
      ],
      "semanticKeys": [
        "OrderId",
        "DeliveryStatus",
        "ReturnId",
        "TicketId"
      ],
      "metrics": {
        "scenarioId": "Q2",
        "title": "배송 지연 영향 분석",
        "highlights": [
          "배송 지연 주문 666건 중 반품 발생 비율은 43.54%이다.",
          "배송 지연 주문의 COMPLAINT 티켓 비율은 31.83%이다."
        ],
        "delayedOrderCount": 666,
        "delayedReturnRatePct": 43.54,
        "delayedComplaintRatePct": 31.83,
        "topDelayedReturnReasons": [
          {
            "reason": "LateDelivery",
            "count": 160
          },
          {
            "reason": "Damaged",
            "count": 124
          },
          {
            "reason": "NotAsDescribed",
            "count": 104
          }
        ]
      },
      "workEvidence": [
        {
          "id": "TM18",
          "source": "Teams",
          "title": "주문 취소율과 배송 지연 상관 점검",
          "businessDate": "2026-05-24T14:00:00+09:00",
          "owner": "한유진",
          "location": "teams/threads.json",
          "target": "campaign-ops"
        },
        {
          "id": "SP06",
          "source": "SharePoint",
          "title": "배송 지연 원인 분석 및 고객 영향",
          "businessDate": "2026-05-23",
          "owner": "윤가영",
          "location": "sharepoint/Operations/06_Delivery_Delay_Root_Cause_and_Customer_Impact.docx",
          "target": "/Track2-Sample/Operations/06_Delivery_Delay_Root_Cause_and_Customer_Impact.docx"
        },
        {
          "id": "EM07",
          "source": "Outlook",
          "title": "반품 사유 월간 요약 - 채널 및 고객등급 검토",
          "businessDate": "2026-05-25T16:30:00+09:00",
          "owner": "배수민",
          "location": "outlook/EM07_returns_message.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "OD05",
          "source": "OneDrive",
          "title": "반품 VOC 분류 워크숍 노트",
          "businessDate": "2026-05-25",
          "owner": "배수민",
          "location": "onedrive/MeetingNotes/05_Return_VOC_Classification_Workshop_Notes.docx",
          "target": "/Track2-Sample/MeetingNotes/05_Return_VOC_Classification_Workshop_Notes.docx"
        },
        {
          "id": "EM06",
          "source": "Outlook",
          "title": "RE: [긴급] 핵심 상품 재고 부족 및 캠페인 노출 조정 요청",
          "businessDate": "2026-05-17T08:50:00+09:00",
          "owner": "윤가영",
          "location": "outlook/EM06_stockout_reply.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "OD03",
          "source": "OneDrive",
          "title": "재고·물류·CS 합동 회의록",
          "businessDate": "2026-05-17",
          "owner": "오지훈",
          "location": "onedrive/MeetingNotes/03_Inventory_Logistics_CS_Joint_Meeting_Notes.docx",
          "target": "/Track2-Sample/MeetingNotes/03_Inventory_Logistics_CS_Joint_Meeting_Notes.docx"
        },
        {
          "id": "TM01",
          "source": "Teams",
          "title": "AeroPhone X 배송 지연 클레임",
          "businessDate": "2026-05-20T09:05:00+09:00",
          "owner": "배수민",
          "location": "teams/threads.json",
          "target": "cs-tier2"
        },
        {
          "id": "TM03",
          "source": "Teams",
          "title": "UltraBook 15 배송 추적 갱신",
          "businessDate": "2026-05-17T08:35:00+09:00",
          "owner": "윤가영",
          "location": "teams/threads.json",
          "target": "logistics"
        }
      ],
      "sourceCoverage": {
        "Teams": 3,
        "SharePoint": 1,
        "Outlook": 2,
        "OneDrive": 2
      },
      "webQuestion": "분석 기간과 배송 지역에 공식 기상 또는 교통 경보가 있었는가?",
      "queryTemplate": "{date_range} {region} 공식 기상 경보와 항공·교통 운영 공지를 찾아 적용 지역과 시간을 URL과 함께 보여줘",
      "interpretationBoundary": "샘플 데이터에 지역이 없으면 외부 사건을 배송 지연의 직접 원인으로 단정하지 않는다.",
      "webEvidence": [
        {
          "id": "WEB-Q2-01",
          "scenarioId": "Q2",
          "title": "National Weather Service Active Alerts API",
          "url": "https://api.weather.gov/alerts/active",
          "domain": "api.weather.gov",
          "sourceType": "official-government-alert",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "활성 기상 경보를 시간과 지역 기준으로 확인할 수 있는 공식 API 예시입니다.",
          "limitations": [
            "현재 특정 경보를 주장하지 않음",
            "샘플 배송 데이터에는 지역 컬럼이 없음"
          ]
        },
        {
          "id": "WEB-Q2-02",
          "scenarioId": "Q2",
          "title": "FAA National Airspace System Status",
          "url": "https://nasstatus.faa.gov/",
          "domain": "nasstatus.faa.gov",
          "sourceType": "official-government-status",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "공항과 국가 공역 운영 이벤트를 확인할 수 있는 공식 상태 출처 예시입니다.",
          "limitations": [
            "현재 운송 장애를 의미하지 않음",
            "워크숍 배송이 항공 운송이라는 근거가 없음"
          ]
        }
      ]
    },
    {
      "id": "Q3",
      "question": "Q3 핵심 상품 3종의 매출/반품 신호를 어떻게 해석할 것인가?",
      "goal": "AeroPhone X/SmartWatch Pro/UltraBook 15 성과 비교",
      "keywords": [
        "AeroPhone X",
        "SmartWatch Pro",
        "UltraBook 15",
        "Q3",
        "제품"
      ],
      "semanticKeys": [
        "ProductId",
        "OrderId",
        "ReturnId"
      ],
      "metrics": {
        "scenarioId": "Q3",
        "title": "핵심 상품 3종 성과 비교",
        "highlights": [
          "Q3 핵심 상품 3종(AeroPhone X, SmartWatch Pro, UltraBook 15)을 동일 기준으로 비교했다.",
          "주문 수, 매출, 반품률을 함께 보고 대응 우선순위를 선정한다."
        ],
        "perProduct": [
          {
            "productName": "AeroPhone X",
            "orderCount": 3,
            "units": 4,
            "salesAmount": 114,
            "returnCount": 1,
            "returnRatePct": 33.33
          },
          {
            "productName": "SmartWatch Pro",
            "orderCount": 2,
            "units": 3,
            "salesAmount": 96.6,
            "returnCount": 0,
            "returnRatePct": 0
          },
          {
            "productName": "UltraBook 15",
            "orderCount": 6,
            "units": 11,
            "salesAmount": 150.7,
            "returnCount": 2,
            "returnRatePct": 33.33
          }
        ]
      },
      "workEvidence": [
        {
          "id": "SP12",
          "source": "SharePoint",
          "title": "Q3 리더십 운영 리스크 브리핑",
          "businessDate": "2026-07-11",
          "owner": "이현지",
          "location": "sharepoint/Leadership/12_Q3_Leadership_Operational_Risk_Briefing.docx",
          "target": "/Track2-Sample/Leadership/12_Q3_Leadership_Operational_Risk_Briefing.docx"
        },
        {
          "id": "EM12",
          "source": "Outlook",
          "title": "RE: BackToSchool 캠페인 조건부 승인 요청",
          "businessDate": "2026-07-11T09:30:00+09:00",
          "owner": "김서연",
          "location": "outlook/EM12_backtoschool_reply.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "OD03",
          "source": "OneDrive",
          "title": "재고·물류·CS 합동 회의록",
          "businessDate": "2026-05-17",
          "owner": "오지훈",
          "location": "onedrive/MeetingNotes/03_Inventory_Logistics_CS_Joint_Meeting_Notes.docx",
          "target": "/Track2-Sample/MeetingNotes/03_Inventory_Logistics_CS_Joint_Meeting_Notes.docx"
        },
        {
          "id": "TM04",
          "source": "Teams",
          "title": "핵심 상품 품절 임박 공동 대응",
          "businessDate": "2026-05-16T09:00:00+09:00",
          "owner": "오지훈",
          "location": "teams/threads.json",
          "target": "inventory"
        },
        {
          "id": "EM05",
          "source": "Outlook",
          "title": "[긴급] 핵심 상품 재고 부족 및 캠페인 노출 조정 요청",
          "businessDate": "2026-05-16T09:15:00+09:00",
          "owner": "오지훈",
          "location": "outlook/EM05_stockout_message.eml",
          "target": "Configured sample recipients"
        },
        {
          "id": "TM01",
          "source": "Teams",
          "title": "AeroPhone X 배송 지연 클레임",
          "businessDate": "2026-05-20T09:05:00+09:00",
          "owner": "배수민",
          "location": "teams/threads.json",
          "target": "cs-tier2"
        },
        {
          "id": "TM03",
          "source": "Teams",
          "title": "UltraBook 15 배송 추적 갱신",
          "businessDate": "2026-05-17T08:35:00+09:00",
          "owner": "윤가영",
          "location": "teams/threads.json",
          "target": "logistics"
        },
        {
          "id": "EM11",
          "source": "Outlook",
          "title": "UltraBook 15 공급 일정 및 고객 공지 기준",
          "businessDate": "2026-05-16T13:45:00+09:00",
          "owner": "오지훈",
          "location": "outlook/EM11_ultrabook-vendor_message.eml",
          "target": "Configured sample recipients"
        }
      ],
      "sourceCoverage": {
        "SharePoint": 1,
        "Outlook": 3,
        "OneDrive": 1,
        "Teams": 3
      },
      "webQuestion": "전자제품 범주의 공식 안전 공지나 사이버보안 지침이 있는가?",
      "queryTemplate": "{date_range} 스마트폰 스마트워치 노트북 범주의 공식 안전 리콜 또는 사이버보안 지침을 URL과 함께 보여줘",
      "interpretationBoundary": "AeroPhone X, SmartWatch Pro, UltraBook 15는 가상 상품이므로 외부 공지는 범주 수준 참고로만 사용한다.",
      "webEvidence": [
        {
          "id": "WEB-Q3-01",
          "scenarioId": "Q3",
          "title": "U.S. Consumer Product Safety Commission Recalls",
          "url": "https://www.cpsc.gov/Recalls",
          "domain": "www.cpsc.gov",
          "sourceType": "official-regulator",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "제품 범주의 공식 리콜 공지를 확인할 수 있는 규제기관 출처 예시입니다.",
          "limitations": [
            "가상 상품에 대한 리콜을 의미하지 않음",
            "실제 제품명과 모델 번호가 일치해야 직접 근거로 사용할 수 있음"
          ]
        },
        {
          "id": "WEB-Q3-02",
          "scenarioId": "Q3",
          "title": "NIST Cybersecurity for IoT Program",
          "url": "https://www.nist.gov/itl/applied-cybersecurity/nist-cybersecurity-iot-program",
          "domain": "www.nist.gov",
          "sourceType": "official-standards-guidance",
          "observedAt": "2026-07-28T15:00:00+09:00",
          "publishedAt": null,
          "scope": "source-capability",
          "factStatus": "fixture-contract",
          "summary": "스마트 연결 제품 범주의 사이버보안 지침을 확인할 수 있는 공식 출처 예시입니다.",
          "limitations": [
            "내부 반품 신호의 원인을 설명하지 않음",
            "스마트워치 등 연결 제품 범주 수준의 참고로만 사용"
          ]
        }
      ]
    }
  ]
} as const
